In [1]:
import torch
print(torch.__version__)

2.4.1


# PyTorch 预备知识
> 由于在 `Chapter0` 中已经比较系统的梳理了一遍 `PyTorch` 相关的知识, 这里仅仅补充教程中没有提到的例子

## torch.Tensor 相关操作
### 广播机制
> 类似于 `numpy` 中的广播机制, 也就是形状不相同的两个张量进行运算的时候, 会发生广播机制
广播机制的工作方式如下:
- 通过适当的元素赋值来扩展一个或者两个数组, 以便在转换之后, 两个张量具有相同的形状
- 对生成的数组按元素操作

In [2]:
# 1. 广播机制
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [3]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 切片操作
> 切片操作和 `Numpy` 以及 `Python` 列表中的切片操作基本一样, 不做过多的描述

## 数据预处理
> 这里可以参考数据分析部分的笔记, 主要是 `pd.DataFrame, pd.Series` 对象的 `dropna, fillna, get_dummies` 等方法的使用

In [8]:
import os
import pandas as pd
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'data.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [9]:
data = pd.read_csv('../data/data.csv')
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [31]:
# 数据清洗部分
# 首先分出特征值和标签值
in1, in2, out = data.iloc[:, 0], data.iloc[:, 1], data.iloc[:, 2]
in1 = in1.fillna(in1.mean())
in2 = pd.get_dummies(in2, dummy_na=True)
print(in1.values)

[3. 2. 4. 3.]
